spring:
  application:
    name: mental-health-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-user-microservice
            uri: http://localhost:8082
            predicates:
              - path=/mental-health-user-auth/**
server:
  port: 9900
logging:
  level:
    org.springframework.security: TRACE
mental:
  health:
    validate-token:
      url: ${VALIDATE_TOKEN_URL}