spring:
  application:
    name: mental-health-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-user-microservice
            uri: http://localhost:8082
            predicates:
              - Path: /mental-health-user-auth/**
server:
  port: 9900